nourish/urls.py
"""URL configuration for nutrition_tracker."""
from __future__ import annotations

from decouple import config
from django.conf import settings
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.templatetags.static import static
from django.urls import include, path
from django.views.generic import RedirectView, TemplateView

from nutrition_tracker import sitemaps
from nutrition_tracker.constants import constants
from nutrition_tracker.views import (
    errors,
    index,
    my_available_foods_ajax,
    my_barcode_ajax,
    my_food,
    my_food_create,
    my_food_delete,
    my_food_edit,
    my_food_log,
    my_food_save_ajax,
    my_foods,
    my_ingredient,
    my_ingredient_log,
    my_meal,
    my_meal_create,
    my_meal_delete,
    my_meal_edit,
    my_mealplan,
    my_meals,
    my_nutrient_ajax,
    my_nutrition,
    my_profile,
    my_recent_foods_ajax,
    my_recipe,
    my_recipe_create,
    my_recipe_delete,
    my_recipe_edit,
    my_recipe_log,
    my_recipes,
    my_serving_ajax,
    my_suggested_foods_ajax,
    my_tracker_ajax,
    nutrient,
    robots_txt,
    search,
    top_foods_ajax,
)

sitemaps_map = {
    "static": sitemaps.StaticSitemap(),
}

urlpatterns = [
    # Include dj_rest_auth URLs before allauth urls, to avoid mangling confirm email URL.
    path("api/", include("nutrition_tracker.urls")),
    path("api/auth/", include("dj_rest_auth.urls")),
    path("api/auth/registration/", include("dj_rest_auth.registration.urls")),
    path("accounts/", include("allauth.urls")),
    path("apple-touch-icon.png", RedirectView.as_view(url=static("nutrition_tracker/img/apple-touch-icon.png"))),
    path(
        "apple-touch-icon-precomposed.png",
        RedirectView.as_view(url=static("nutrition_tracker/img/apple-touch-icon-precomposed.png")),
    ),
    path("cookie_policy/", TemplateView.as_view(template_name="docs/cookie_policy.html"), name="cookie_policy"),
    path("favicon.ico", RedirectView.as_view(url=static("nutrition_tracker/img/favicon.ico"))),
    path(config("ADMIN_PATH"), admin.site.urls),
    path(
        "my_available_foods_ajax/<int:id>/",
        my_available_foods_ajax.MyAvailableFoodsAjaxView.as_view(),
        name="my_available_foods_ajax",
    ),
    path("my_barcode_ajax/<str:c>/", my_barcode_ajax.MyBarcodeAjaxView.as_view(), name="my_barcode_ajax"),
    path("my_food/<uuid:id>/", my_food.MyFoodView.as_view(), name=constants.URL_DETAIL_FOOD),
    path("my_food_create/", my_food_create.MyFoodCreateView.as_view(), name=constants.URL_CREATE_FOOD),
    path("my_food_delete/", my_food_delete.MyFoodDeleteView.as_view(), name=constants.URL_DELETE_FOOD),
    path("my_food_edit/<uuid:id>/", my_food_edit.MyFoodEditView.as_view(), name=constants.URL_EDIT_FOOD),
    path("my_food_log/<uuid:id>/", my_food_log.MyFoodLogView.as_view(), name=constants.URL_LOG_FOOD),
    path("my_food_save_ajax/", my_food_save_ajax.MyFoodSaveAjaxView.as_view(), name="my_food_save_ajax"),
    path("my_foods/", my_foods.MyFoodsView.as_view(), name=constants.URL_MY_FOODS),
    path("my_ingredient/<uuid:id>/", my_ingredient.MyIngredientView.as_view(), name=constants.URL_DETAIL_INGREDIENT),
    path(
        "my_ingredient/<uuid:id>/<uuid:mid>/",
        my_ingredient.MyIngredientView.as_view(),
        name=constants.URL_DETAIL_INGREDIENT,
    ),
    path(
        "my_ingredient_log/<uuid:id>/",
        my_ingredient_log.MyIngredientLogView.as_view(),
        name=constants.URL_LOG_INGREDIENT,
    ),
    path(
        "my_ingredient_log/<uuid:id>/<uuid:mid>/",
        my_ingredient_log.MyIngredientLogView.as_view(),
        name=constants.URL_LOG_INGREDIENT,
    ),
    path("my_meal/<uuid:id>/", my_meal.MyMealView.as_view(), name=constants.URL_DETAIL_MEAL),
    path("my_meal_create/", my_meal_create.MyMealCreateView.as_view(), name=constants.URL_CREATE_MEAL),
    path("my_meal_delete/", my_meal_delete.MyMealDeleteView.as_view(), name=constants.URL_DELETE_MEAL),
    path("my_meal_edit/<uuid:id>/", my_meal_edit.MyMealEditView.as_view(), name=constants.URL_EDIT_MEAL),
    path("my_mealplan/", my_mealplan.MyMealplanView.as_view(), name=constants.URL_MY_MEALPLAN),
    path("my_mealplan/<int:step>/", my_mealplan.MyMealplanView.as_view(), name=constants.URL_MY_MEALPLAN),
    path("my_meals/", my_meals.MyMealsView.as_view(), name=constants.URL_MY_MEALS),
    path("my_nutrient_ajax/<uuid:id>/", my_nutrient_ajax.MyNutrientAjaxView.as_view(), name="my_nutrient_ajax"),
    path("my_nutrition/", my_nutrition.MyNutritionView.as_view(), name=constants.URL_NUTRITION),
    path("my_profile/", my_profile.MyProfileView.as_view(), name=constants.URL_PROFILE),
    path(
        "my_recent_foods_ajax/<int:id>/",
        my_recent_foods_ajax.MyRecentFoodsAjaxView.as_view(),
        name="my_recent_foods_ajax",
    ),
    path("my_recipe/<uuid:id>/", my_recipe.MyRecipeView.as_view(), name=constants.URL_DETAIL_RECIPE),
    path("my_recipe/<uuid:id>/<uuid:mid>/", my_recipe.MyRecipeView.as_view(), name=constants.URL_DETAIL_RECIPE),
    path("my_recipe_create/", my_recipe_create.MyRecipeCreateView.as_view(), name=constants.URL_CREATE_RECIPE),
    path("my_recipe_delete/", my_recipe_delete.MyRecipeDeleteView.as_view(), name=constants.URL_DELETE_RECIPE),
    path("my_recipe_edit/<uuid:id>/", my_recipe_edit.MyRecipeEditView.as_view(), name=constants.URL_EDIT_RECIPE),
    path("my_recipe_log/<uuid:id>/", my_recipe_log.MyRecipeLogView.as_view(), name=constants.URL_LOG_RECIPE),
    path(
        "my_recipe_log/<uuid:id>/<uuid:mid>/", my_recipe_log.MyRecipeLogView.as_view(), name=constants.URL_LOG_RECIPE
    ),
    path("my_recipes/", my_recipes.MyRecipesView.as_view(), name=constants.URL_MY_RECIPES),
    path("my_serving_ajax/<uuid:id>/", my_serving_ajax.MyServingAjaxView.as_view(), name="my_serving_ajax"),
    path(
        "my_suggested_foods_ajax/",
        my_suggested_foods_ajax.MySuggestedFoodsAjaxView.as_view(),
        name="my_suggested_foods_ajax",
    ),
    path("my_tracker_ajax/<int:id>/", my_tracker_ajax.MyTrackerAjaxView.as_view(), name="my_tracker_ajax"),
    path("nutrient/<int:id>/", nutrient.NutrientView.as_view(), name=constants.URL_NUTRIENT),
    path("privacy_policy/", TemplateView.as_view(template_name="docs/privacy_policy.html"), name="privacy_policy"),
    path("robots.txt", robots_txt.robots_txt),
    path("search/", search.SearchResultsView.as_view(), name=constants.URL_SEARCH),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps_map}, name="django.contrib.sitemaps.views.sitemap"),
    path("terms_of_use/", TemplateView.as_view(template_name="docs/terms_of_use.html"), name="terms_of_use"),
    path("top_foods_ajax/<int:id>/", top_foods_ajax.TopFoodsAjaxView.as_view(), name="top_foods_ajax"),
    path("", index.HomepageView.as_view(), name=constants.URL_HOME),
]

handler404 = errors.NotFoundErrorView.as_view()
handler500 = errors.handler500

if settings.DJANGO_ENV == "dev":
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

nutrition_tracker/urls.py
"""URL configuration for nutrition_tracker API."""
from __future__ import annotations

from django.urls import include, path, re_path
from rest_framework import routers

from nutrition_tracker.rest_framework.views import (
    APIAppConstants,
    APIDeleteUserIngredient,
    APIDeleteUserMeal,
    APIDeleteUserRecipe,
    APIDetailsDBFood,
    APIDetailsUserIngredient,
    APIDetailsUserMeal,
    APIDetailsUserRecipe,
    APIEditUserIngredient,
    APIEditUserMeal,
    APIEditUserRecipe,
    APILogDBFood,
    APILogUserIngredient,
    APILogUserRecipe,
    APIMealplanFormOne,
    APIMealplanFormThree,
    APIMealplanFormTwo,
    APIMyFoods,
    APIMyMeals,
    APIMyNutrition,
    APIMyRecipes,
    APINutrient,
    APINutritionFDA,
    APINutritionLabel,
    APINutritionPreference,
    APISaveDBFood,
    APISearchResults,
    APITracker,
)

router = routers.SimpleRouter()

urlpatterns = [
    path("", include(router.urls)),
    path("config/appconstants/", APIAppConstants.as_view(), name="api_app_constants"),
    path("config/nutrition/fda/", APINutritionFDA.as_view(), name="api_nutrition_fda"),
    path("config/nutrition/label/", APINutritionLabel.as_view(), name="api_nutrition_label"),
    path("delete/useringredient/<uuid:id>/", APIDeleteUserIngredient.as_view(), name="api_delete_user_ingredient"),
    path(
        "delete/useringredient/<uuid:id>/<uuid:mid>/",
        APIDeleteUserIngredient.as_view(),
        name="api_delete_user_ingredient",
    ),
    path("delete/usermeal/<uuid:id>/", APIDeleteUserMeal.as_view(), name="api_delete_user_meal"),
    path("delete/userrecipe/<uuid:id>/", APIDeleteUserRecipe.as_view(), name="api_delete_user_recipe"),
    path("delete/userrecipe/<uuid:id>/<uuid:mid>/", APIDeleteUserRecipe.as_view(), name="api_delete_user_recipe"),
    path("details/dbfood/<uuid:id>/", APIDetailsDBFood.as_view(), name="api_details_db_food"),
    path("details/useringredient/<uuid:id>/", APIDetailsUserIngredient.as_view(), name="api_details_user_ingredient"),
    path(
        "details/useringredient/<uuid:id>/<uuid:mid>/",
        APIDetailsUserIngredient.as_view(),
        name="api_details_user_ingredient",
    ),
    path("details/usermeal/<uuid:id>/", APIDetailsUserMeal.as_view(), name="api_details_user_meal"),
    path("details/userrecipe/<uuid:id>/", APIDetailsUserRecipe.as_view(), name="api_details_user_recipe"),
    path("details/userrecipe/<uuid:id>/<uuid:mid>/", APIDetailsUserRecipe.as_view(), name="api_details_user_recipe"),
    path("edit/useringredient/", APIEditUserIngredient.as_view(), name="api_edit_user_ingredient"),
    path("edit/useringredient/<uuid:id>/", APIEditUserIngredient.as_view(), name="api_edit_user_ingredient"),
    path("edit/usermeal/", APIEditUserMeal.as_view(), name="api_edit_user_meal"),
    path("edit/usermeal/<uuid:id>/", APIEditUserMeal.as_view(), name="api_edit_user_meal"),
    path("edit/userrecipe/", APIEditUserRecipe.as_view(), name="api_edit_user_recipe"),
    path("edit/userrecipe/<uuid:id>/", APIEditUserRecipe.as_view(), name="api_edit_user_recipe"),
    path("log/dbfood/<uuid:id>/", APILogDBFood.as_view(), name="api_log_db_food"),
    path("log/useringredient/<uuid:id>/", APILogUserIngredient.as_view(), name="api_log_user_ingredient"),
    path("log/useringredient/<uuid:id>/<uuid:mid>/", APILogUserIngredient.as_view(), name="api_log_user_ingredient"),
    path("log/userrecipe/<uuid:id>/", APILogUserRecipe.as_view(), name="api_log_user_recipe"),
    path("log/userrecipe/<uuid:id>/<uuid:mid>/", APILogUserRecipe.as_view(), name="api_log_user_recipe"),
    path("myfoods/", APIMyFoods.as_view(), name="api_my_foods"),
    path("mymeals/", APIMyMeals.as_view(), name="api_my_meals"),
    path("mynutrition/", APIMyNutrition.as_view(), name="api_my_nutrition"),
    path("myrecipes/", APIMyRecipes.as_view(), name="api_my_recipes"),
    path("nutrient/<int:id>/", APINutrient.as_view(), name="api_nutrient"),
    path("nutrient/<int:id>/<int:days>/", APINutrient.as_view(), name="api_nutrient"),
    path("preferences/nutrition/", APINutritionPreference.as_view(), name="api_nutrition_preference"),
    path("savedbfood/", APISaveDBFood.as_view(), name="api_save_db_food"),
    path("savemealplan/formone/", APIMealplanFormOne.as_view(), name="api_mealplan_form_one"),
    path("savemealplan/formtwo/", APIMealplanFormTwo.as_view(), name="api_mealplan_form_two"),
    path("savemealplan/formthree/", APIMealplanFormThree.as_view(), name="api_mealplan_form_three"),
    path("search/", APISearchResults.as_view(), name="api_search"),
    re_path(r"^tracker/(?P<td>\d{4}-\d{2}-\d{2})/$", APITracker.as_view(), name="api_tracker"),
]

nutrition_tracker/models/db_food_portion.py
"""Model and APIs for DB food portion metadata.

Data schema: {USDAFood, ...} => {DBFood} => {UserIngredient}
"""
from __future__ import annotations

import uuid
from typing import Any, MutableMapping

from django.core.validators import MinValueValidator
from django.db import models
from django.db.models import QuerySet

from nutrition_tracker.constants import constants
from nutrition_tracker.database import models as db_models
from nutrition_tracker.models import db_food, id_base


class DBFoodPortion(id_base.IdBase):
    """DB Model for db food portion metadata."""

    db_food = models.ForeignKey(
        db_food.DBFood,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name="db_food",
        help_text="DB Food for this food portion.",
    )
    source_id = models.PositiveBigIntegerField(
        null=True,
        blank=True,
        verbose_name="source_id",
        help_text=(
            "Unique (per food) permanent identifier of the row "
            "in source dataset. For e.g. id for USDA Food Portions."
        ),
    )
    source_type = models.PositiveSmallIntegerField(
        default=constants.DBFoodSourceType.UNKNOWN,
        choices=constants.DBFoodSourceType.choices,
        verbose_name="source_type",
        help_text="Food source type.",
    )
    external_id = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    servings_per_container = models.FloatField(
        null=True,
        blank=True,
        validators=[MinValueValidator(0.0)],
        verbose_name="servings_per_container",
        help_text="The number of servings per container.",
    )
    serving_size = models.FloatField(
        null=True,
        blank=True,
        validators=[MinValueValidator(0.0)],
        verbose_name="serving_size",
        help_text="The amount of the serving size when expressed as gram or ml.",
    )
    serving_size_unit = models.CharField(
        max_length=25,
        null=True,
        blank=True,
        verbose_name="serving_size_unit",
        help_text="The unit used to express the serving size (gram or ml).",
    )
    quantity = models.FloatField(
        null=True,
        blank=True,
        validators=[MinValueValidator(0.0)],
        verbose_name="quantity",
        help_text=("The quantity of portions used as specified by the user."),
    )
    amount = models.FloatField(
        null=True,
        blank=True,
        validators=[MinValueValidator(0.0)],
        verbose_name="amount",
        help_text=(
            "The number of measure units that comprise the measure " "(e.g. if measure is 3 tsp, the amount is 3)."
        ),
    )
    measure_unit_id = models.PositiveIntegerField(
        null=True,
        blank=True,
        verbose_name="measure_unit_id",
        help_text=("The unit used for the measure (e.g. if measure is 3 tsp, " "the unit is tsp)."),
    )
    portion_description = models.TextField(
        null=True,
        blank=True,
        verbose_name="portion_description",
        help_text=(
            "Foundation foods: Comments that provide more specificity "
            "on the measure. For example, for a pizza measure the "
            "dissemination text might be 1 slice is 1/8th of a 14 "
            "inch pizza. "
            "Survey (FNDDS) foods: The household description of the portion."
        ),
    )
    modifier = models.TextField(
        null=True,
        blank=True,
        verbose_name="modifier",
        help_text=(
            "Foundation foods: Qualifier of the measure (e.g. related "
            "to food shape or form) (e.g. melted, crushed, diced). "
            "Survey (FNDDS) foods: The portion code. "
            "SR legacy foods: description of measures, including the "
            'unit of measure and the measure modifier (e.g. waffle round (4" dia)).'
        ),
    )

    class Meta(id_base.IdBase.Meta):
        db_table = "db_food_portion"
        constraints = [
            models.UniqueConstraint(
                name="%(app_label)s_%(class)s_one_per_db_food_source_id_type",
                fields=["db_food", "source_id", "source_type"],
            ),
        ]


def empty_qs() -> QuerySet[DBFoodPortion]:
    """Empty QuerySet."""
    return db_models.empty_qs(DBFoodPortion)


def _load_queryset() -> QuerySet[DBFoodPortion]:
    """Base QuerySet for db food portions. All other APIs filter on this queryset."""
    return DBFoodPortion.objects.select_related("db_food")


def load_portion(id_: int | None = None, external_id: str | uuid.UUID | None = None) -> DBFoodPortion | None:
    """Loads a db food portion object."""
    params: dict[str, Any] = {}
    if id_:
        params["id"] = id_
    if external_id:
        params["external_id"] = external_id

    return db_models.load(DBFoodPortion, _load_queryset(), params)


def load_portions(
    ids: list[int] | None = None,
    external_ids: list[str | uuid.UUID] | None = None,
    db_food_ids: list[int] | None = None,
) -> QuerySet[DBFoodPortion]:
    """Batch load db food portion objects."""
    if not ids:
        ids = []
    if not external_ids:
        external_ids = []
    if not db_food_ids:
        db_food_ids = []

    qs: QuerySet[DBFoodPortion] = _load_queryset()

    params: dict[str, Any] = {}
    if ids:
        params["id__in"] = ids
    if external_ids:
        params["external_id__in"] = external_ids
    if db_food_ids:
        params["db_food_id__in"] = db_food_ids

    return db_models.bulk_load(qs, params)


def create(**kwargs: Any) -> DBFoodPortion:
    """Create and save a db food portion in the database."""
    return db_models.create(DBFoodPortion, **kwargs)


def update_or_create(defaults: MutableMapping[str, Any] | None = None, **kwargs: Any) -> tuple[DBFoodPortion, bool]:
    """Update a db food portion with the given kwargs, creating a new one if necessary."""
    return db_models.update_or_create(DBFoodPortion, defaults=defaults, **kwargs)

templates/nutrition_tracker/includes/branded_food_details.html
{% load i18n %}
{% load utils %}

{% display_brand_field 'brand_owner' as brand_owner %}
{% if brand_owner %}
<div class="{{ wrapper_class }} pt-2">
  <div class="{{ label_class }}">
    {% translate "Brand owner" %}
  </div>
  <div class="{{ value_class }}">
    {{ brand_owner }}
  </div>
</div>
{% endif %}

{% display_brand_field 'brand_name' as brand_name %}
{% if brand_name %}
<div class="{{ wrapper_class }} pt-2">
  <div class="{{ label_class }}">
    {% translate "Brand name" %}
  </div>
  <div class="{{ value_class }}">
    {{ brand_name }}
  </div>
</div>
{% endif %}

{% display_brand_field 'subbrand_name' as subbrand_name %}
{% if subbrand_name %}
<div class="{{ wrapper_class }} pt-2">
  <div class="{{ label_class }}">
    {% translate "Subbrand name" %}
  </div>
  <div class="{{ value_class }}">
    {{ subbrand_name }}
  </div>
</div>
{% endif %}

{% display_brand_field 'gtin_upc' as gtin_upc %}
{% if gtin_upc %}
<div class="{{ wrapper_class }} pt-2">
  <div class="{{ label_class }}">
    {% translate "GTIN/UPC" %}
  </div>
  <div class="{{ value_class }}">
    {{ gtin_upc }}
  </div>
</div>
{% endif %}

{% display_brand_field 'ingredients' as ingredients %}
{% if ingredients %}
<div class="{{ wrapper_class }} pt-2">
  <div class="{{ label_class }}">
    {% translate "Ingredients" %}
  </div>
  <div class="{{ value_class }}">
    <span class="font-size-12 d-inline-block">{{ ingredients }}</span>
  </div>
</div>
{% endif %}

templates/nutrition_tracker/includes/create_prompt.html
{% load utils %}

<div class="jumbotron py-4 d-flex justify-content-between mb-3">
  <div class="ml-2 mr-auto w-75">
    <div class="lead">{{ prompt }}</div>
    <div class="text-muted">{{ subprompt }}</div>
  </div>
  <div class="d-flex align-items-center"><a class="btn btn-primary btn-sm" href="{% url buttonurl %}">{{ buttontext }}</a></div>
</div>

templates/nutrition_tracker/includes/food_details.html
{% load i18n %}
{% load utils %}

{% if lfood and lfood.category_id %}
<div class="{{ wrapper_class }} pt-2">
  <div class="{{ label_class }}">
    {% translate "Category" %}
  </div>
  <div class="{{ value_class }}">
    {{ lfood.category_id|display_category_name }}
  </div>
</div>
{% elif cfood and cfood.food_category_id %}
<div class="{{ wrapper_class }} pt-2">
  <div class="{{ label_class }}">
    {% translate "Category" %}
  </div>
  <div class="{{ value_class }}">
    {{ cfood.food_category_id|display_category_name }}
  </div>
</div>
{% endif %}

templates/nutrition_tracker/includes/items_module.html
{% load utils %}

<ul class="item-list-main list-group list-group-flush {{ wrapper_class }}">
  {% for item_lobject in item_lobjects %}
  {% with item_lobject|get_classname as modelclass %}
  {% if modelclass == MODEL_CLASS_LFOOD %}
  {% include 'nutrition_tracker/includes/module_food_item.html' with item_lfood=item_lobject %}
  {% endif %}
  {% if modelclass == MODEL_CLASS_LRECIPE %}
  {% include 'nutrition_tracker/includes/module_food_item.html' with item_lrecipe=item_lobject %}
  {% endif %}
  {% endwith %}
  {% endfor %}

  {% for item_cfood in item_cfoods %}
  {% include 'nutrition_tracker/includes/module_food_item.html' with item_cfood=item_cfood %}
  {% endfor %}
</ul>

<script type="text/javascript">
  $(document).ready(function() {
      initTooltips();
  });
</script>

templates/nutrition_tracker/includes/kitchen_items.html
{% load static %}

<li class="list-group-item d-flex justify-content-between align-items-center min-item-height">
  <div class="mr-auto w-75">
    <a class="text-reset" href="{% url detailurl kitchenobject.external_id %}">
      <div class="font-weight-normal">{{ maintext }}</div>
      <small class="text-muted">{{ subtext }}</small>
    </a>
  </div>
  {% include 'nutrition_tracker/includes/item_buttons.html' with kitchenobject=kitchenobject logurl=logurl logtext=logtext editurl=editurl edittext=edittext deleteurl=deleteurl deletetext=deletetext %}
</li>

templates/nutrition_tracker/includes/kitchen_prompt.html
{% load i18n %}
{% load utils %}

<div class="row justify-content-between align-items-center mx-auto mt-3 mb-4">
  <div class="mr-auto p-2 w-75">
    <p class="display-5 mb-0">{{ header }}</p>
    {% url URL_PROFILE as profile_url %}
    <small>{% blocktranslate %}Add family members in your <a href="{{ profile_url }}" class="text-decoration-none">profile</a> to share foods and recipes.{% endblocktranslate %}</small>
  </div>
  <div class="d-flex">
    <div class="dropdown">
      <a class="btn btn-sm btn-primary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	{% translate "Add" %}
      </a>

      <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
	<a class="dropdown-item" href="{% url primaryurl %}">{{ primarytext }}</a>
	<a class="dropdown-item" href="{% url secondaryurl1 %}">{{ secondarytext1 }}</a>
	<a class="dropdown-item" href="{% url secondaryurl2 %}">{{ secondarytext2 }}</a>
      </div>
    </div>
  </div>
</div>

templates/nutrition_tracker/includes/nutrition_label_row.html
{% load utils %}

{% get_nutrient_amount nutrient_id label_type as nutrient_amount %}
{% normalize_portion_size nutrient_amount as normalized_amount %}
{% get_rdi_amount nutrient_id as dv_amount %}

<div class="row justify-content-between font-size-smaller nutrient nutrient-{{ nutrient_id }} {% if normalized_amount is None and not ismodify %}d-none{% endif %}" data-nutrient="{{ nutrient_id }}">
  <div class="col-9 text-left pl-2">
    <span class="nutrient-name">{{ nutrient_id|display_nutrient_name }}</span>
    {% spaceless %}
    <span class="nutrient-quantity">{% if normalized_amount is not None %}{{ normalized_amount|floatformat:FLOATFORMAT_PRECISION }}{% endif %}</span><span class="nutrient-unit {% if normalized_amount is None %}d-none{% endif %}">{{ nutrient_id|display_nutrient_unit }}</span>
    {% endspaceless %}
  </div>

  <div class="col-3 text-right pr-1">
    {% spaceless %}
    <span class="font-weight-bold nutrient-dv">{% if normalized_amount is not None and dv_amount is not None %}{% widthratio normalized_amount dv_amount 100 %}{% endif %}</span><span class="font-weight-bold nutrient-dv-percent {% if normalized_amount is None or dv_amount is None %}d-none{% endif %}">&percnt;</span>
    {% endspaceless %}
  </div>
</div>

<div class="row justify-content-center {% if normalized_amount is None and not ismodify %}d-none{% endif %}">
  <div class="col-12 px-1">
    <div class="border-bottom border-dark"></div>
  </div>
</div>

templates/nutrition_tracker/includes/portion_details.html
{% load i18n %}
{% load utils %}

<div class="{{ wrapper_class }}">
  <div class="{{ label_class }} my-auto">
    {% translate "Serving Size" %}
  </div>
  <div class="{{ value_class }}">
    <select id="id_serving" class="form-control" onchange="updateNutrients()">
      {% for display_portion in food_portions %}
      <option {% if default_portion.0 == display_portion.0 %}selected{% endif %} value="{{ display_portion.0 }}" data-gm-wt="{{ display_portion.2 }}" data-wt-unit="{{ display_portion.3 }}">{{ display_portion.1}}</option>
      {% endfor %}
    </select>
  </div>
</div>

<div class="{{ wrapper_class }}">
  <div class="{{ label_class }} my-auto">
    {% translate "Total Servings" %}
  </div>
  <div class="{{ value_class }}">
    <input type="number" name="quantity" min="0" step="any" onchange="updateNutrients()" class="numberinput form-control" id="id_quantity" value="{{ default_portion_quantity }}">
  </div>
</div>